volumes:
  postgres-data:

networks:
  backend:

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
      no_cache: true
    container_name: postgres
    hostname: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5